name: germs_blaster
channels:
  - conda-forge
  - base
  - bioconda
dependencies:
  - wget=1.20.3
  - snakemake=7.18.2
  - graphviz=6.0.1
  - coreutils>=9.1
  - requests>=2.28
  - anaconda::pymongo=3.12.0
  - jupyter
  - pip
  - python-dotenv
  - pip:
    - pymongo[srv]